// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4JHfP3l8qQOopWhnxjNU0zds-F6q4z3Q',
    appId: '1:145036418788:web:dddeb06bb8fb4ab50556f1',
    messagingSenderId: '145036418788',
    projectId: 'adopet-b8bf1',
    authDomain: 'adopet-b8bf1.firebaseapp.com',
    storageBucket: 'adopet-b8bf1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpgcJTvl2iJBV_d6iILz0_t9Y63tMWwtY',
    appId: '1:145036418788:android:f2531318b6c588ba0556f1',
    messagingSenderId: '145036418788',
    projectId: 'adopet-b8bf1',
    storageBucket: 'adopet-b8bf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZU77DBXV1kYc8u8_mBjMSclVADfoRGjU',
    appId: '1:145036418788:ios:a3dddfe1d859af070556f1',
    messagingSenderId: '145036418788',
    projectId: 'adopet-b8bf1',
    storageBucket: 'adopet-b8bf1.firebasestorage.app',
    iosBundleId: 'com.example.adopet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZU77DBXV1kYc8u8_mBjMSclVADfoRGjU',
    appId: '1:145036418788:ios:a3dddfe1d859af070556f1',
    messagingSenderId: '145036418788',
    projectId: 'adopet-b8bf1',
    storageBucket: 'adopet-b8bf1.firebasestorage.app',
    iosBundleId: 'com.example.adopet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4JHfP3l8qQOopWhnxjNU0zds-F6q4z3Q',
    appId: '1:145036418788:web:9ef3cf34316ac4800556f1',
    messagingSenderId: '145036418788',
    projectId: 'adopet-b8bf1',
    authDomain: 'adopet-b8bf1.firebaseapp.com',
    storageBucket: 'adopet-b8bf1.firebasestorage.app',
  );

}